Add message handling for sending objects
fix-project/fix pull request #110
Opened 2023-10-16 02:18 UTC by yhdengh

2023-10-17 19:17 UTC, Akshay-Srivatsan requested changes
This doesn't seem to work with the `fixpoint-server` and `fixpoint-client` testers (they throw various exceptions depending on what I'm trying to eval).  We should probably debug that before merging…

2023-10-17 19:17 UTC, Akshay-Srivatsan commented on src/runtime/message.hh
> +  Message( const Opcode opcode, std::string_view payload );
Are there lifetime constraints on the `string_view` (e.g., does the backing data have to outlive the `Message`)? We should document them if so.

2023-10-17 19:17 UTC, Akshay-Srivatsan commented on src/runtime/message.hh
> +    assert( holds_alternative<Blob>( payload_ ) );
Does `assert` actually do anything? We never define `NDEBUG`.

2023-10-17 19:17 UTC, Akshay-Srivatsan commented on src/runtime/runtimestorage.cc
> +Handle RuntimeStorage::add_canonical_blob( Blob&& blob )
Maybe `add_and_canonicalize_blob`?  A "canonical blob" isn't a thing, which is what the current name implies.  Also do we really need this over just calling `canonicalize` after `add_blob`?  `RuntimeStorage` already has a huge public API, we should probably consider making it smaller…

2023-10-17 19:17 UTC, Akshay-Srivatsan commented on src/runtime/network.cc
> +  runtime_.storage().visit( task.handle(), std::bind( &Remote::send_object, this, placeholders::_1 ) );
This might need the optional boolean parameters to `RuntimeStorage::visit` set to false?

2023-10-17 19:44 UTC, yhdengh commented on src/runtime/message.hh
> +  Message( const Opcode opcode, std::string_view payload );
Yes -- (if in the future we do anything along the line of reference counting, these messages should also be counted as a reference.) I could potentially add a owning-version of `send_data`.

2023-10-18 05:54 UTC, Akshay-Srivatsan approved these changes
lgtm, I think we should mark this as closing #106 and create new issues for "Fixpoint figures out what data to send" and "scheduler figures out what data to send".

If you add "closes #106" to the PR description I think it'll link them automatically, otherwise there's probably a button somewhere.

2023-10-18 16:06 UTC, merged