Refactor local and canonical storage
fix-project/fix pull request #117
Opened 2023-10-24 00:43 UTC by yhdengh

Sequenced after #116 

* Refactor RuntimeStorage such that objects with canonical names only
  exist in canonical_storage_, and local_storage_ holds the canonical
  Name after a local Name is canonicalized.

* NetworkWorker inserts dependency between the canonical Task and the
  local Task after canonicalizing a Task.

* When DependencyGraph gets dependencies from the FixCache, it checks
  both the local and canonical version if the task has been
  canonicalized.

* Finishing a local Task also finishes the canonical Task if it has been
  canonicalized.

2023-10-24 01:09 UTC, Akshay-Srivatsan requested changes
I think we should think through the abstraction/separation of concerns more.  A lot of this logic is more general and should be abstracted away to reduce bugs later (and it doesn't seem like the networking part of the codebase should be responsible for the "insert dependency when canonicalizing" concern).

2023-10-24 01:09 UTC, Akshay-Srivatsan commented on src/runtime/network.cc
> +  }
This logic shouldn't be in `Remote`, we're going to need it everywhere we canonicalize anything.  I think we should have `Handle Runtime::canonicalize(Handle)` and `Task Runtime::canonicalize(Task)` which take care of this internally—it's going to be so hard to debug if every time anyone in Fixpoint canonicalizes anything they also have to remember to manually insert a dependency in the graph (e.g., when `RuntimeStorage` serializes objects to disk).  Or `RuntimeStorage` could do it automatically, if it takes a reference to the dependency graph.

Maybe we should also have `Handle Runtime::add(variant<Blob,Tree,Tag,Thunk>)` and `variant<Blob,Tree,Tag,Thunk> Runtime::get(Handle)`, and not expose `RuntimeStorage` at all?  That way it's impossible to circumvent any of these required automatic things.

2023-10-24 01:09 UTC, Akshay-Srivatsan commented on src/runtime/dependency_graph.cc
> +std::optional<Handle> DependencyGraph::get_cache( Task& task )
Maybe `get_cached_result`?  Or maybe `FixCache` should do this internally.

2023-10-24 01:09 UTC, Akshay-Srivatsan commented on src/runtime/dependency_graph.hh
> +  std::optional<Handle> start_after( Task& target, Task& blocked, bool start = true );
This param should have an `@param` listing.

2023-10-24 01:09 UTC, Akshay-Srivatsan commented on src/runtime/runtimestorage.cc
>    Handle name( local_id, tree.size(), ContentType::Tree );
Not relevant to this PR, but `tree.size()` is a use-after-move.  This repeats in a the other `add_*` functions too.

2023-10-24 02:51 UTC, yhdengh commented on src/runtime/network.cc
> +  }
It is messy to have this logic here, and actually I am not sure whether having a dependency entry between the local and the canonical version of a Task is the right way to go. The dependency relationship here is not really `start_after`, but they are equivalent, more like the `continue_after` in the old version of `Fixcache`. And we need to check for both the local and canonical version of the Task at multiple places, hard to get it right (actually I just realized there is a bug when I am typing this).

Another way of Implementation that I considered is making `Remote` track a "translation table" between local Tasks and canonical Tasks it has seen, and translate canonical Tasks to local Tasks when it call into any of the `Runtime` API functions, such that only one of the local version and canonical version of a Task exists in `FixCache` and `DependencyGraph`. Canonical handles canonicalized from local handles are limited to RuntimeStorage and Remote only. What do you think?

2023-10-24 18:21 UTC, Akshay-Srivatsan commented on src/runtime/network.cc
> +  }
Hm, I'm still iffy on having `Remote` be responsible for the translation table.  It feels like the best places for it would be:
- `DependencyGraph` since this is maintaining an invariant that's necessary for the graph's correctness; it doesn't necessarily need to be an entry like `Apply`/`Eval`/`Fill`, but could be an extra table that's consulted when necessary
- `RuntimeStorage` since it deals with canonicalizing and looking up names anyway

Potentially a bigger issue is that translating canonical names to local names isn't well-defined—many different local names can correspond to the same canonical name.  If we pick a single local name to use, we wouldn't meaningfully solve the problem (there'd still be duplicated work).

One workaround we could do is *always* compute the canonical name of an object as soon as it's added to `RuntimeStorage`, but also create a local name (if one doesn't already exist for the same object) and return that.  Then there'd be a 1:1 mapping between canonical and local names.  I think it would be cleaner to always use canonical names though, if we can get the map to be performant?  We're using the same type of map anyway for FixCache, which I think we hit much more often, so it seems like we have a much bigger problem if our map is slow...

If we do decide that FixCache (and by extension DependencyGraph and RuntimeWorker) can only handle Local Names, I'd say we should make Local and Canonical Names different C++ types, where the only way to convert from one to the other is to ask `RuntimeStorage` (or `NameManager` or something).  Otherwise my guess is that we're going to get a bunch of weird bugs from canonical names leaking into fixcache because we forgot an if statement somewhere.

2023-10-25 21:19 UTC, Akshay-Srivatsan approved these changes
looks good, just the naming things I mentioned in-person

2023-10-25 21:47 UTC, merged