Merge fix-viewer into source tree
fix-project/fix pull request #118
Opened 2023-10-27 03:07 UTC by Tweoss

Modifies http-server to allow file serving of the compiled fix-viewer. 
Adds multiple connection support to http-tester

2023-10-30 22:48 UTC, Akshay-Srivatsan requested changes
I think a big thing here is including instructions on how to run the visualizer (both on stagecast.org and on other machines), and making the conditional build logic less implicit.

2023-10-30 22:48 UTC, Akshay-Srivatsan commented on src/tester/http-client/src/handle.rs
> +    /// Also takes d9|0|4|0 for compatibility with fixpoint handle formatting.
Can we make this also just take a 64-character hex string and interpret it verbatim?  Also, we should have a test to make sure the Rust impl and the C++ impl interpret Handles the same way.

2023-10-30 22:48 UTC, Akshay-Srivatsan commented on src/tester/http-client/src/main.rs
> +fn main() -> eframe::Result<()> {
So does this actually work/has this been tested on not-Wasm?

2023-10-30 22:48 UTC, Akshay-Srivatsan commented on src/tester/CMakeLists.txt
> +
Also `http-tester` should probably be built regardless, since that's only C++ (and otherwise it might be forgotten during refactors).

2023-11-09 20:24 UTC, Tweoss commented on src/tester/http-client/src/app.rs
> +        #[cfg(not(target_arch = "wasm32"))] // no File->Quit on web pages!
<img width="781" alt="image" src="https://github.com/fix-project/fix/assets/70821802/8e76a174-2eb3-4f1e-9fbc-c1b302ed622f">
After a tiny bit of fixing, yes!

2023-11-29 20:06 UTC, Akshay-Srivatsan requested changes
A few more things regarding building.

Also could you document what "parent" and "child" mean vs. "dependee"?

2023-11-30 21:52 UTC, Tweoss commented on src/tester/http-client/README.md
There doesn't seem to be a license, but I added a reference

2024-01-26 19:05 UTC, closed without merging