Add curry application and test
fix-project/fix pull request #133
Opened 2023-11-15 19:52 UTC by sebastianingino

- Adds a `curry` application that can curry a program with a variadic number of arguments
  - Takes a compiled function and number of needed arguments as parameters, returns a curried function
  -  Successive calls of the compiled function bind the parameters in order and either return a new function, or the final result if the number of required arguments is met
- Tested with `add-simple`
- Adds declaration for `create_tag` to `fixpoint_util.h`
- Adds helper `get_i32_ro_mem` to `fixpoint_util.h` and `fixpoint_util.c`

2023-11-16 20:07 UTC, yhdengh commented on .gitignore
> +/boot
This may not be necessary since we remove `boot/` in newer versions of bootstrap

2023-11-16 20:21 UTC, Akshay-Srivatsan requested changes
This looks great overall, nice work!  I have a few questions about what arguments are acceptable for `curry`—we want to make sure that any function can be used as an argument, including already-partially-applied functions.

2023-11-16 20:21 UTC, Akshay-Srivatsan commented on applications/curry/curry.cc
> +  if ( get_value_type( get_ro_table_0( 1 ) ) == Tag ) { // Un-curried function
Doesn't this assume that the uncurried function must not already have arguments applied?  I'm not sure that's always true—I think we'd be okay with an ENCODE procedure (i.e., a function with some arguments already applied) being the target of curry.

Maybe curry could return a tag, and check for that tag when it's called again to determine what to do?  (Any tag generated by any other procedure would be ignored/treated as an ENCODE).  Or maybe there's a recursive formulation here, and the base case is when there's zero arguments left to curry. @yhdengh do you have any other ideas?

2023-11-16 20:21 UTC, Akshay-Srivatsan commented on src/tests/test-curry.cc
> +  memcpy( &result, add_two_result.literal_blob().data(), sizeof( uint32_t ) );
This should probably be `memcpy( &result, rt.storage().get_blob( add_two_result ).data(), sizeof( uint32_t ) );`, in case the result somehow wasn't constructed as a literal blob (which *should* never happen, but technically it isn't incorrect if it does).

2023-11-16 20:21 UTC, Akshay-Srivatsan commented on src/tests/test-curry.cc
> +}
One additional test might be to check that you can curry `curry` itself.  E.g., `(((curry curry 2) addblob) 2)` should do the same thing as `(curry addblob 2)`.

2023-11-16 20:23 UTC, yhdengh reviewed
Great work!

Also:
* In the `@return` comments of `apply` and `run`, instead of saying "the result of running the program if a fully apply", it makes more sense to say something along the line of "thunk to the full apply" since `curry` does not actually do the work.

2023-11-16 20:23 UTC, yhdengh commented on applications/curry/curry.cc
> +
Extra blank line.

2023-11-16 20:23 UTC, yhdengh commented on applications/curry/curry.cc
> +
Extra blank line

2023-11-16 20:23 UTC, yhdengh commented on applications/curry/curry.cc
> + * @return externref - a callable curried function, resource_limits if the program was aborted, or the
```suggestion
 * @return externref - a callable curried function, resource_limits if the program was aborted, or a full apply if enough arguments are provided
```

2023-11-16 20:32 UTC, yhdengh commented on applications/curry/curry.cc
> +  if ( get_value_type( get_ro_table_0( 1 ) ) == Tag ) { // Un-curried function
Or I think this line is actually checking whether the "top-level procedure" of the current ENCODE is the curry-runnable-tag or not? Correct me if I am wrong, but it looks to me this would also work if we are currying a ENCODE procedure (it should be at `get_ro_table_0(2)`).

For the return value of `curry` though, I think returning a tag that says whether the curry is successful or not would be a bit cleaner...The current implementation return the `resource_limit` blob when it fails to grow the table, but it never checks whether it is trying to `curry` a blob.

2023-11-21 06:53 UTC, sebastianingino commented on applications/curry/curry.cc
> +  if ( get_value_type( get_ro_table_0( 1 ) ) == Tag ) { // Un-curried function
If curry is called as an ENCODE (argument 1), it acts as the curried function, assumes that this internal ENCODE has the parameters (curried_program, num_args, bound_args*), and binds new arguments. If it's called as a tag, it assumes that it's being called directly and curries the provided function (either tag or ENCODE form). As of writing, ENCODE-form programs wouldn't work because of a bug in `run`, but I'll fix that. @yhdengh @Akshay-Srivatsan I'm not sure if I'm missing something but I haven't been able to get any tags to be directly runnable?

2023-12-04 23:35 UTC, yhdengh commented on applications/curry/curry.cc
> +  set_i32_rw_mem_0( 0, succeeded );
We actually have an API function for this? `create_blob_i32` can create a Blob from a i32 without storing the i32 in a `rw_memory`.

2023-12-04 23:35 UTC, yhdengh commented on src/runtime/worker.hh
> +   * @param handle                  The handle to get the runnable tag from.
Maybe `get the procedure (as a runnable tag) from an ENCODE` or something along that line? Since we are looking for a very specific runnable tag.

2024-01-08 20:53 UTC, yhdengh approved these changes
lgtm

2024-01-18 21:32 UTC, Akshay-Srivatsan approved these changes
lgtm2

2024-01-18 21:58 UTC, merged